backend:
  name: git-gateway
  repo: sepaen/site
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: projects
    label: Projects
    folder: content/projects
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: Type, name: type, widget: hidden, default: project }
      - { label: Published, name: published, widget: boolean, default: false }
      - { label: Date, name: date, required: false, widget: datetime }
      - {
          label: Short title (as shown in project URL),
          name: title,
          widget: string,
        }
      - { label: Title, name: fulltitle, required: false, widget: text }
      - { label: Subtitle, name: subtitle, required: false, widget: text }
      - {
          label: Color,
          name: color,
          required: false,
          default: '',
          widget: color,
        }
      - { label: Cover, name: cover, widget: image }
      - label: Images
        name: images
        widget: list
        required: false
        fields:
          - { label: Image, name: image, widget: image }
      - { label: Body, name: body, widget: markdown }

  - name: jobs
    label: Jobs
    folder: content/jobs
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: Type, name: type, widget: hidden, default: job }
      - { label: Published, name: published, widget: boolean, default: false }
      - { label: Date, name: date, widget: datetime }
      - { label: Title, name: title, widget: text }
      - { label: Description, name: description, widget: text }
      - {
          label: Requirements,
          name: requirements,
          required: false,
          widget: text,
        }
      - { label: 'How to apply', name: howto, required: false, widget: text }

  - name: pages
    label: Pages
    files:
      - label: Contact Page
        name: contact
        file: content/pages/contact.md
        editor:
          preview: false
        fields:
          - { label: type, name: type, widget: hidden, default: contact }
          - { label: Title, name: title, widget: string }
          - { label: Email, name: email, widget: string }
          - name: phone
            label: Phone numbers
            widget: list
            fields:
              - { label: Number, name: number, widget: string }
          - name: social
            label: Social networks
            widget: list
            fields:
              - { label: Platform, name: platform, widget: string }
              - { label: URL, name: url, widget: string }

      - label: 'About Page'
        name: about
        file: content/pages/about.md
        editor:
          preview: false
        fields:
          - { label: type, name: type, widget: hidden, default: about }
          - { label: Body, name: body, widget: markdown }

      - label: 'No jobs available'
        name: nojobs
        file: content/pages/no-jobs.md
        editor:
          preview: false
        fields:
          - { label: type, name: type, widget: hidden, default: nojobs }
          - { label: Text, name: text, widget: text }
