backend:
  name: git-gateway
  repo: sepaen/site
  branch: master

media_folder: static/assets

collections:
  - name: projects
    label: Projects
    folder: content/projects
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Slug, name: slug, widget: string}
      - {label: Date, name: date, widget: datetime}
      - {label: Description, name: description, widget: string}
      - {label: "Client website", name: url, widget: string}
      - {label: Extra information, name: extra, widget: string}
      - {label: Color, name: color, widget: string}
      - {label: Images, name: images, widget: image}
      - {label: Title, name: title, widget: string}
      - {label: Body, name: body, widget: markdown}

